samsung-cnct/kraken-lib

ansible/roles/kraken.provider/kraken.provider.aws/templates/kraken.provider.aws.tf.jinja2
=> Encouraging terraform to deploy etcd before masters/nodes

Documentation/cloud-configs/template-examples/master/manifests/apiserver.yaml, Documentation/working-example/master/apiserver.yaml, ansible/roles/kraken.master/kraken.master.docker/templates/api-server-manifest.yaml.jinja2
=> set admission control per http://kubernetes.io/docs/admin/admission-controllers/#is-there-a-recommended-set-of-plug-ins-to-use

ansible/roles/kraken.config/filter_plugins/gz.py
force all calls to gzip to happen an arbitrary, fixed time
=> make gz calls idemptotent

ansible/roles/kraken.services/templates/service-values.yaml.jinja2
to use multi level yaml values to kraken service.
=> modify service value template. to use multi level yaml values.

ansible/roles/kraken.provider/kraken.provider.aws/templates/kraken.provider.aws.module.vpc.tf.jinja2
=> add a map for us regions for dns suffix setting

Documentation/kraken-configs/etcd.md, Documentation/samples/standard_cluster.yaml, Documentation/security/example/config.yaml, ansible/roles/kraken.config/files/config.yaml
=> bump etcd version to 3.1.0

ansible/roles/kraken.services/tasks/kill-services.yaml
@davidewatson was right, hitting rate limit
=> Back off retry period

ansible/down.yaml, ansible/roles/kraken.config/defaults/main.yaml, ansible/roles/kraken.config/tasks/main.yaml, ansible/up.yaml
Move The config_file definition to kraken.config and add the completely
missing config_file_default
=> Make config_file definition consistent

README.md
Added a blurb about what and where YOURCLUSTER means in general, since it was never truly defined and was difficult to understand at first as an outside.
Ideally i do not like having things mentioned outside the order of which it can happen, but I understand when writing it can be difficult to organize, so I wanted to add some clarity to a few places to make sure that order of operations does matter, yeah we can debate that point as obvious, but clarity is preferable than assuming something is obvious.
=> A small change to readme for clarity

README.md
just another thing i noticed when trying to use the tool.
=> removed typo: g.kraken should be .kraken

ansible/roles/kraken.etcd/kraken.etcd.docker/templates/etcd.units.kraken-etcd-ssl.part.jinja2, ansible/roles/kraken.master/kraken.master.docker/templates/units.kraken-apiserver-ssl.part.jinja2, ansible/roles/kraken.node/kraken.node.docker/templates/units.kraken-worker-ssl.part.jinja2
this will let us use k2 in us-east-2
=> upgrade drunkensmee to v0.5

down.sh, lib/common.sh, up.sh, update.sh
Also rename `bin/utils.sh` `lib/common.sh`
=> Use the actual cluster name in the help text

ansible/roles/kraken.config/files/config.yaml
balancer only applies to API servers.
=> Fold loadBalancerConfig into apiServerConfig since this load

hack/dockerdev, lib/bashrc
Cherry pick hack/dockerdev changes from master
=> K2r update dockerdev

README.md
updated k2 documentation to include instructions to upgrade master nodes
=> upgrade documentation

ansible/roles/kraken.upgrade/kraken.upgrade.aws/filter_plugins/kill_node.py, ansible/roles/kraken.upgrade/kraken.upgrade.aws/tasks/aws-control-plane.yaml
aws region had been set from user's aws cred file, now it grabs the region out of the config
=> aws region now set from config

Documentation/kraken-configs/clusterservices.md, Documentation/kraken-configs/deployment.md, Documentation/security/example/config.yaml, ansible/roles/kraken.config/files/config.yaml, ansible/roles/kraken.services/defaults/main.yaml, ansible/roles/kraken.services/tasks/kill-dns.yaml, ansible/roles/kraken.services/tasks/main.yaml, ansible/roles/kraken.services/tasks/run-dns.yaml, ansible/roles/kraken.services/templates/dns.yaml.jinja2, ansible/roles/kraken.services/templates/v1.4/dns.yaml.jinja2, ansible/roles/kraken.services/templates/v1.5/dns.yaml.jinja2, ansible/roles/kraken.services/templates/v1.6/dns.yaml.jinja2
Split DNS into a direct (non-helm service).
=> k2-283 DNS separation

ansible/roles/kraken.config/tasks/main.yaml, ansible/roles/kraken.config/tasks/setup.yaml, ansible/roles/kraken.nodePool/kraken.master.docker/tasks/service-account-key.yaml
this removes unused variables mentioned in https://github.com/samsung-cnct/k2/issues/375
=> removed non-used loops vars

Documentation/kraken-configs/dns.md, ansible/roles/kraken.config/files/config.yaml, ansible/roles/kraken.config/files/gke-config.yaml
=> Corrected namsepace to namespace

Jenkinsfile, ansible/roles/kraken.config/tasks/main.yaml, ansible/roles/kraken.fabric/kraken.fabric.flannel/tasks/main.yaml, lib/common.sh
=> Fix dryrun for flannel tasks

ansible/roles/kraken.cluster_common/tasks/main.yaml, ansible/roles/kraken.cluster_common/templates/help.txt.jinja2, lib/common.sh
=> Add complete help text for cluster config

ansible/roles/kraken.services/tasks/kill-services.yaml
https://github.com/samsung-cnct/k2/issues/268
=> Fix walk of status object when killing services

ansible/roles/kraken.services/tasks/kill-services.yaml
=> Revert "Fix walk of status object when killing services"

ansible/roles/kraken.services/defaults/main.yaml, ansible/roles/kraken.services/tasks/run-dns.yaml, ansible/roles/kraken.services/templates/rbac-dns-policy.yaml.jinja2, ansible/roles/kraken.services/templates/v1.6/dns.yaml.jinja2, ansible/roles/kraken.services/templates/v1.6/rbac-dns-policy.yaml.jinja2
Correct typos
add rbac
move to 1.6 versions needed
=> 446 1.6 DNS changes

ansible/roles/kraken.fabric/kraken.fabric.flannel/tasks/main.yaml, ansible/roles/kraken.services/tasks/kill-services.yaml, ansible/roles/kraken.services/tasks/run-services.yaml
Method now checks for an error in stdout instead of checking for a failure, which means no more ignored errors will show up as failures when they were expected to fail. 
This is for issue https://github.com/samsung-cnct/k2/issues/372
=> errors are now ignored on up

ansible/roles/kraken.config/files/config.yaml, ansible/roles/kraken.config/files/gke-config.yaml, ansible/roles/kraken.fabric/kraken.fabric.flannel/tasks/main.yaml, ansible/roles/kraken.fabric/kraken.fabric.flannel/templates/canal.yaml.part.jinja2, ansible/roles/kraken.fabric/kraken.fabric.flannel/templates/v1.6/README.md, ansible/roles/kraken.fabric/kraken.fabric.flannel/templates/v1.6/canal.yaml.part.jinja2, ansible/roles/kraken.fabric/kraken.fabric.flannel/templates/v1.6/config.yaml.part.jinja2, ansible/roles/kraken.nodePool/kraken.master.docker/tasks/render-manifests.yaml, ansible/roles/kraken.nodePool/kraken.master.docker/templates/v1.6/controller-manager-manifest.yaml.jinja2
Update to required newer fabric setup.
=> 435 Newer 1.6 fabric changes

ansible/roles/kraken.rbac/tasks/bootstrap-default-rbac-policy.yaml, ansible/roles/kraken.rbac/tasks/build-access.yaml, ansible/roles/kraken.services/tasks/run-dns.yaml
=> rbac 16 hotfix

schemas/config/v1/cluster.json, schemas/config/v1/loadBalancerConfig.json
adds a max to clusterName, and a min to ensure that there is something there, as well as a length check for ELBs
=> added length checks

README.md, ansible/roles/kraken.config/files/config.yaml, ansible/roles/kraken.config/files/gke-config.yaml, ansible/roles/kraken.config/filter_plugins/is_empty.py, ansible/roles/kraken.config/tasks/helm-versioning.yaml, ansible/roles/kraken.services/tasks/kill-services.yaml
After chatting with @davidewatson, we are currently not making changes to the schema, because they would be breaking changes. 
This means we don't currently verify against garbage input on helmOverride in the config file (it should be empty, true, or false) but other than that, this should work better.
=> Helmcleanup

Jenkinsfile
According to
https://common-jenkins.kubeme.io/job/K2/pipeline-syntax/globals#env the
correct variable name is BRANCH_NAME instead of BRANCH
Fixes #483
=> The environment variable should be BRANCH_NAME

ansible/roles/kraken.config/files/config.yaml, ansible/roles/kraken.config/files/gke-config.yaml
#491 
Add rbacKubeAuth example stanza that can be used when needed.
=> add rbac stanza for use when needed 491

ansible/roles/kraken.config/files/config.yaml, build-scripts/update-generated-config.sh, schemas/config/v1/awsProviderConfig.json, schemas/config/v1/awsSubnetConfig.json
documentation and defaults. Fixes #465.
=> Change default region to us-east-1 and update schema with

ansible/roles/kraken.fabric/kraken.fabric.flannel/tasks/main.yaml, ansible/roles/kraken.provider/kraken.provider.aws/tasks/main.yaml, ansible/roles/kraken.provider/kraken.provider.gke/tasks/create-cluster.yaml, ansible/roles/kraken.provider/kraken.provider.gke/tasks/main.yaml, ansible/roles/kraken.ssh/kraken.ssh.selector/tasks/main.yaml
Reverts samsung-cnct/k2#501
This never passed CI and fails dryrun test. Should not have been merged into master.
=> Revert "Dryrun tags bug fixing"

ansible/roles/kraken.services/templates/rbac-dns-policy.yaml.jinja2
=> missed change on original checkin

ansible/roles/kraken.fabric/kraken.fabric.flannel/tasks/main.yaml, ansible/roles/kraken.nodePool/kraken.master.docker/templates/v1.6/controller-manager-manifest.yaml.jinja2, ansible/up.yaml
=> fix fabric issues

ansible/roles/kraken.clean/tasks/main.yaml
=> Fix kraken.clean failure after ansible upgrade

Documentation/tags/README.md
adds documentation for tag added in #534
=> add fabric_only to tag docs

ansible/roles/kraken.fabric/kraken.fabric.flannel/tasks/main.yaml, ansible/roles/kraken.fabric/kraken.fabric.flannel/templates/namespace.yaml.part.jinja2, ansible/roles/kraken.fabric/kraken.fabric.weave/tasks/main.yaml, ansible/roles/kraken.fabric/kraken.fabric.weave/templates/namespace.yaml.part.jinja2
#541 and partial #540 
Add namespace.yaml and create using apply.
Remove api server up check
=> #541 remove namespace dance and extra api up check

README.md
This should cover all documentation for K2 in regards to node management. This is meant to cover issue #230 .
We should make sure to document upcoming changes to k2cli as well.
=> Documentation for K2 node management and services

Jenkinsfile, build-scripts/custom-jnlp/Dockerfile, build-scripts/custom-jnlp/Makefile, build-scripts/custom-jnlp/README.md
turning some knobs to get our failure rate to be based on kubernetes failures or k2 failures and not apparent jenkins networking issues.
=> Attempt to stabilize CI runs

schemas/config/v1/weaveFabricNetwork.json
as mentioned in: https://github.com/samsung-cnct/k2/issues/555
=> added required target link to added schema json object.

ansible/roles/kraken.fabric/kraken.fabric.weave/templates/v1.6/weave.yaml.part.jinja2, ansible/roles/kraken.fabric/kraken.fabric.weave/templates/weave.yaml.part.jinja2, schemas/config/v1/weaveFabricNetwork.json
details: https://github.com/kubernetes/kubernetes/issues/2763
=> Weave-net yaml problem, addressed because of known and reported apiserver issue 

ansible/roles/kraken.config/files/config.yaml
=> Fix coreOs version to ensure the tested version is the same one the

ansible/roles/kraken.config/files/config.yaml, hack/parallel-conformance.sh
=> rev CoreOS version and sort out e2e.go params

ansible/roles/kraken.provider/kraken.provider.aws/tasks/aws-action-dryrun.yaml, ansible/roles/kraken.provider/kraken.provider.aws/tasks/main.yaml
Add terraform dryrun role on kraken.provider
Related to [samsung-cnct/k2-tools/pull/78](https://github.com/samsung-cnct/k2-tools/pull/78)
=> Add terraform dryrun role on kraken.provider

down.sh, lib/common.sh, up.sh, update.sh
if ansible failures occur on up or down, send data to crashapp.
Related: 
The crash app: https://github.com/samsung-cnct/k2-crash-application/pull/1
K2-tools integration: https://github.com/samsung-cnct/k2-tools/pull/57
=> Revisions to check for k2 failures and trigger crash app

hack/dockerdev
Add an option to freshen the docker image when running dockerdev.
=> Add fresh option to dockerdev

ansible/roles/kraken.nodePool/kraken.nodePool.master/tasks/render-write-files.yaml, ansible/roles/kraken.services/tasks/run-services.yaml
Easy ticket. Get rid of unnecessary debugs.
Others look like they are intended
=> remove unnecessary debugs

Jenkinsfile
=> do not used cached layers for k2 image build

ansible/roles/kraken.config/files/config.yaml, ansible/roles/kraken.provider/kraken.provider.aws/templates/kraken.provider.aws.module.etcd.tf.jinja2, ansible/roles/kraken.provider/kraken.provider.aws/templates/kraken.provider.aws.module.master.tf.jinja2, ansible/roles/kraken.provider/kraken.provider.aws/templates/kraken.provider.aws.module.node.tf.jinja2, ansible/roles/kraken.provider/kraken.provider.aws/templates/kraken.provider.aws.module.subnet.tf.jinja2, schemas/config/v1/awsNodeProviderConfig.json, schemas/config/v1/awsSubnetConfig.json
work in progress. 
Intention is to resolve: https://github.com/samsung-cnct/cts-k8s-2017/issues/35 
and partially related to: https://github.com/samsung-cnct/k2/issues/634
=> Allow for toggle of public Ips in subnet and Launch Configs.

Jenkinsfile
env.GIT_URL does not exist, so the test against it was always failing. Use the correct env variable and test it against 'samsung-cnct' not 'samsung_cnct'.
=> Compare against the correct env and string for publishing

Jenkinsfile
test to see if the CHANGE_URL has the github org rather than the quay org
Also increase the verbosity of the negative case message.
=> Now test the right variable

Jenkinsfile
The environment variables do not exist for doing this in the master branch. Use the scm object.
Fixes #655
=> retreive uri and test against it

README.md
=> made a note about k2-crash-app data collection

README.md
https://github.com/samsung-cnct/k2cli/issues/118
=> Update README.md to fix documentation on environment variables for k2 and k2cli

Jenkinsfile, ansible/roles/kraken.provider/kraken.provider.aws/tasks/wait-for-etcd.yaml
=> remove extraneous space

README.md
How to spinup small cluster for dev or research
fixes https://github.com/samsung-cnct/k2/issues/621
related: https://github.com/samsung-cnct/k2cli/pull/123
=> instructions on how to spin up a non-ha cluster

README.md, ansible/roles/kraken.config/files/config.yaml, ansible/roles/kraken.nodePool/kraken.nodePool.master/templates/units.kraken-apiserver-ssl.part.jinja2, ansible/roles/kraken.provider/kraken.provider.aws/templates/apiserver-loadbalancer-ssl-certificate-options.conf.jinja2, schemas/config/v1/cluster.json
Related to: https://github.com/samsung-cnct/drunkensmee/pull/1
Fixes: samsung-cnct/k2#636
=> added ability to add custom domain name to k8s api server elb

Jenkinsfile, ansible/roles/kraken.config/files/config.yaml, ansible/roles/kraken.readiness/tasks/do-wait.yaml
recommendations (t2.large). Fixes #670.
=> Increase etcd instance sizes to conform with published CoreOS

Documentation/kraken-configs/helmconfigs.md, ansible/roles/kraken.services/tasks/run-services.yaml, schemas/config/v1/helmConfig.json, schemas/config/v1/helmRegistries.json, schemas/config/v1/helmRegistry.json
Add the ability to use private helm app registries
Fixes #657
=> helm: login to app registry

ansible/roles/kraken.fabric/kraken.fabric.flannel/templates/v1.6/rbac-canal-policy.yaml.jinja2, ansible/roles/kraken.fabric/kraken.fabric.flannel/templates/v1.7/rbac-canal-policy.yaml.jinja2
new rbac roles etc needed for 1.6/1.7 canal
=> Issue #728 Fix canal rbac deny

Jenkinsfile
default will be to use helm if available but the override env var will allow the check to pass if helm is not present by not running helm
=> allow for helm check to always pass.  

ansible/roles/kraken.provider/kraken.provider.aws/tasks/main.yaml, ansible/roles/kraken.provider/kraken.provider.aws/tasks/terraform-apply-etcd.yaml, ansible/roles/kraken.provider/kraken.provider.aws/tasks/wait-for-etcd.yaml
added loop var for clarity and consistency, added -out for terraform plan to fix https://github.com/samsung-cnct/k2/issues/689
=> added nodepool loop var and -out param for terraform plan

roadmap.md
closes #250 as this is a better way to track our roadmap
=> port roadmap doc from issue to repo

ansible/roles/kraken.config/files/config.yaml, ansible/roles/kraken.config/files/gke-config.yaml
fixes https://github.com/samsung-cnct/k2/issues/604
=> calico version to 1.3.0

bin/max_k8s_version.sh
the ansible playbook that gets called will create this file, don't insist it exist already.
=> the file shouldn't exist, it will be created by the ansible command

ansible/roles/kraken.config/files/config.yaml
Initial work for: https://github.com/samsung-cnct/k2/issues/620
=> Update etcd versions

CODEOWNERS
Let's see if this causes PR's to actually be assigned to reviewers
=> Tighten up CODEOWNERS syntax

Jenkinsfile
caompare the value of the quated maybe empty env var to "null"
=> when you quote a null string, you get "null" not a falsey value

Jenkinsfile, ansible/roles/kraken.config/files/config.yaml, build-scripts/custom-jnlp/Dockerfile
This PR is associated w/the on-call version check for week 8/14 samsung-cnct/issues#38
=> updating k8s to 1.7.4

Jenkinsfile
please see: https://github.com/samsung-cnct/issues/issues/46 for reasons
=> gke processes are no-ops

ansible/roles/kraken.nodePool/kraken.nodePool.etcd/tasks/main.yaml, ansible/roles/kraken.nodePool/kraken.nodePool.etcd/templates/etcd.units.etcd-prediscovery.part.jinja2, ansible/roles/kraken.nodePool/kraken.nodePool.etcd/templates/etcd.units.etcd.part.jinja2
=> Add a systemd unit to wait for the number of srv records expected

schemas/config/v1/canalFabricContainers.json, schemas/config/v1/fabricConfig.json, schemas/config/v1/weaveFabricConfig.json
=> Fix up usage of oneOf so that it only occurs in place of entire

ansible/roles/kraken.nodePool/kraken.nodePool.master/templates/v1.5/units.kubelet.part.jinja2, ansible/roles/kraken.nodePool/kraken.nodePool.master/templates/v1.6/units.kubelet.part.jinja2, ansible/roles/kraken.nodePool/kraken.nodePool.master/templates/v1.7/units.kubelet.part.jinja2, ansible/roles/kraken.nodePool/kraken.nodePool.node/templates/units.kubelet.part.jinja2, ansible/roles/kraken.nodePool/kraken.nodePool.node/templates/v1.5/units.kubelet.part.jinja2, ansible/roles/kraken.nodePool/kraken.nodePool.node/templates/v1.6/units.kubelet.part.jinja2, ansible/roles/kraken.nodePool/kraken.nodePool.node/templates/v1.7/units.kubelet.part.jinja2
=> Set node labels for all supported versions of k8s (fixes #750).

Jenkinsfile, ansible/roles/kraken.config/files/gke-config.yaml
k2 resolution for samsung-cnct/issues#46
=> enable gke ci, move to us-east1

ansible/roles/kraken.provider/kraken.provider.aws/tasks/aws-action-dryrun.yaml, ansible/roles/kraken.provider/kraken.provider.aws/tasks/aws-action.yaml, ansible/roles/kraken.provider/kraken.provider.aws/tasks/main.yaml, ansible/roles/kraken.provider/kraken.provider.aws/tasks/terraform-apply-etcd.yaml
=> Selectively target k8s tf targets to avoid unintended changes to

ansible/roles/kraken.config/files/config.yaml
while etcd discovery problems are addressed. Also update comments.
=> Change kraken defaults to stand up a non-HA cluster to unblock CI

ansible/roles/kraken.config/tasks/set-oidc-info.yaml, ansible/roles/kraken.provider/kraken.provider.gke/tasks/destroy-cluster.yaml, ansible/roles/kraken.provider/kraken.provider.gke/tasks/process-cluster.yaml
(cf. https://github.com/openshift/openshift-ansible/pull/5287).
=> Do not use jinja2 templates in ansible when statements

ansible/roles/kraken.config/files/gke-config.yaml
=> bump default GKE version to 1.6.9

ansible/roles/kraken.cluster_common/tasks/locksmith.yaml, ansible/roles/kraken.cluster_common/templates/locksmith.part.jinja2, ansible/roles/kraken.config/files/gke-config.yaml
=> Unconditionally configure the locksmith reboot_strategy to off

ansible/roles/kraken.cluster_common/tasks/locksmith.yaml, ansible/roles/kraken.cluster_common/templates/locksmith.part.jinja2
=> Revert "Unconditionally configure the locksmith reboot_strategy to off"

Jenkinsfile, ansible/roles/kraken.config/files/config.yaml
=> update k8s version from v1.7.4 to v1.7.5

.pre-commit-config.yaml, Jenkinsfile, ansible/roles/kraken.access/tasks/generate-admin-cert.yaml, ansible/roles/kraken.access/tasks/generate-admin-kubeconfig.yaml, ansible/roles/kraken.access/tasks/generate-user-cert-config.yaml, ansible/roles/kraken.access/tasks/setup-certs.yaml, ansible/roles/kraken.assembler/tasks/nodes.yaml, ansible/roles/kraken.config/tasks/check-update.yaml, ansible/roles/kraken.config/tasks/per-cluster-setup.yaml, ansible/roles/kraken.config/tasks/set-oidc-info.yaml, ansible/roles/kraken.fabric/kraken.fabric.selector/tasks/fabric-type.yaml, ansible/roles/kraken.post/tasks/mark-clusters-status.yaml, ansible/roles/kraken.rbac/tasks/build-access.yaml, ansible/roles/kraken.readiness/tasks/do-wait.yaml, ansible/roles/kraken.readiness/tasks/setup-readiness.yaml, ansible/roles/kraken.services/tasks/generate-oidc-cert.yaml, ansible/roles/kraken.services/tasks/kill-dns.yaml, ansible/roles/kraken.services/tasks/kill-services.yaml, ansible/roles/kraken.services/tasks/run-dns.yaml, ansible/roles/kraken.services/tasks/run-services.yaml, hack/dockerdev
* Fix ansible lint errors
* Add ansible lint checking to Jenkins
Fixes #827
=> Add ansible linting to Jenkins

Jenkinsfile, ansible/roles/kraken.config/files/config.yaml
For weekly oncall version check.
https://github.com/samsung-cnct/issues/issues/48
=> updated k8s versions

ansible/roles/kraken.config/tasks/main.yaml, ansible/roles/kraken.config/tasks/validate-config.yaml
=> added check for existence of config file and added proper error message

README.md
=> remove capital K2 from quay repo name

ansible/roles/kraken.ssh/kraken.ssh.aws/tasks/main.yaml
add security token to the bastion node discovery stanza
=> add security token to finding bastion nodes

ansible/roles/kraken.services/defaults/main.yaml
=> use the correct version of dnsmasq image for 1.5 clsuters

ansible/roles/kraken.fabric/kraken.fabric.flannel/tasks/main.yaml, ansible/roles/kraken.fabric/kraken.fabric.weave/tasks/main.yaml, ansible/roles/kraken.rbac/tasks/bootstrap-default-rbac-policy.yaml, ansible/roles/kraken.services/tasks/create-storage-class.yaml, ansible/roles/kraken.services/tasks/run-dns.yaml, ansible/roles/kraken.update/kraken.update.aws/tasks/update-cluster.yaml
Also cleaned up unnecessary task in update-cluster.yaml.
=> added --record to all kubectl apply calls in krakenlib

ansible/roles/kraken.services/tasks/create-storage-class.yaml
=> missing not added

bin/computed_kubectl.sh, bin/down.sh, bin/max_k8s_version.sh, bin/ssh_command.sh, bin/up.sh, bin/update.sh, lib/common.sh, lib/kraken_arguments.sh
improved handling of flags, and easier code to read, in general creating better handling or arguments that are being passed. Also included recommendations from previous PR.  Changes in kraken as aresult to be referenced here. 
Note this doesnt change tools, just improves usage and deterministic behavior.
=> [Refactor] computedkubectl and ssh_command

Documentation/tags/README.md
I didn't know if this should be `~`, `$HOME` or is there another convention we should use here?
=> anonymize docs

ansible/roles/kraken.config/defaults/main.yaml
Added dns_only to deafults file
=>  changed defaults

ansible/roles/kraken.services/tasks/create-storage-class.yaml
Addresses https://github.com/samsung-cnct/kraken-lib/issues/898
=> More reliable creation of storageclass

ansible/roles/kraken.nodePool/kraken.nodePool.master/templates/basicauth.csv.jinja2
needed to add the leading stanza to work with the new write-files
format
=> let basicauth work again

README.md
edited README to reflect new ETCD structure
=> updated README to reflect new etcd structure

ansible/roles/kraken.config/files/gke-config.yaml
https://cloud.google.com/container-engine/release-notes
=> Update GKE k8s version to 1.7.9 to avoid downgrade after creation.

ansible/roles/kraken.services/tasks/main.yaml
=> Create storage classes before running services since some charts

ansible/roles/kraken.provider/kraken.provider.aws/templates/kraken.provider.aws.module.node.tf.jinja2
not defined or false (fixes #958).
=> Provide default min_size and max_size values when autoscaling is

ansible/roles/kraken.config/files/config.yaml, ansible/roles/kraken.services/tasks/run-services.yaml
nodes (see #963 for discussion).
=> Change cluster autoscaling defaults to off with a minimum of 3

ansible/roles/kraken.update/kraken.update.aws/tasks/update-cluster.yaml, ansible/roles/kraken.update/kraken.update.aws/tasks/update-nodes.yaml
fixes https://github.com/samsung-cnct/kraken-lib/issues/962
=> added kubectl

Jenkinsfile, README.md, lib/common.sh, lib/kraken_arguments.sh
Added `--provider` flag to allow users to specify `GKE` config instead of default `AWS`
Fixes: https://github.com/samsung-cnct/kraken-lib/issues/926
=> gke config file generation

build-scripts/e2etester-docker/Dockerfile
checksum verification for gsutil and google-cloud-sdk
fixes https://github.com/samsung-cnct/kraken-lib/issues/399
=> added checksum

Jenkinsfile, README.md, ansible/roles/kraken.config/files/config-private-topology.yaml, ansible/roles/kraken.config/files/config.yaml, ansible/roles/kraken.config/files/gke-config.yaml, ansible/roles/kraken.config/tasks/helm.yaml, schemas/config/v1/cluster.json
=> Updated how we handle helm usage

ansible/roles/kraken.cluster_common/tasks/cluster-start.yaml, ansible/roles/kraken.cluster_common/tasks/ssh_check.yaml
As specified in config.yaml
Fixes: #324
=> Tasks to check that private and public ssh keys exist

ansible/roles/kraken.config/files/config.yaml
Weave was tested manually with the following process:
- brought up cluster
- deployed an nginx pod on it
- successfully accessed said pod from a different node with curl
=> update weave version

ansible/roles/kraken.cluster_common/templates/docker-install.part.jinja2
schema has 'uri' so we'll go with that.
=> make template agree with schema

README.md, SUPPORT.md
And other stuff that made no sense
=> Fixed some spelling mistakes

.gitlab-ci.yml
docker tag and push had been set to k2 instead of ${REGISTRY}
=> bug fix in .gitlab

README.md, ansible/roles/kraken.services/tasks/kill-services.yaml, ansible/roles/kraken.services/tasks/manage-services.yaml
fixes https://github.com/samsung-cnct/kraken-lib/issues/975
=> update tiller namespace for down.sh tasks

.gitlab-ci.yml, ansible/roles/kraken.config/files/config.yaml
1.8.5 was released.  we should be defaulting to it.
part of samsung-cnct/issues#97
=> move to 1.8.5

ansible/roles/kraken.config/files/config.yaml
tested manually, still works!
part of samsung-cnct/issues#97
=> update default weave config

.gitlab-ci.yml
@samba  this was your catch from earlier today
=> .gitlab publish fix

.gitlab-ci.yml
Extend artifact retention for configuration data.
=> Set artifact retention to 2-weeks

.gitlab-ci.yml, Documentation/security/README.md, Documentation/security/example/cnct.yaml, ansible/library/compatibility.py, ansible/roles/kraken.config/files/config.yaml, ansible/roles/kraken.fabric/kraken.fabric.flannel/templates/rbac-canal-policy.yaml.jinja2, ansible/roles/kraken.fabric/kraken.fabric.flannel/templates/v1.6/canal.yaml.part.jinja2, ansible/roles/kraken.fabric/kraken.fabric.flannel/templates/v1.7/canal.yaml.part.jinja2, ansible/roles/kraken.fabric/kraken.fabric.flannel/templates/v1.7/rbac-canal-policy.yaml.jinja2, ansible/roles/kraken.fabric/kraken.fabric.flannel/templates/v1.8/canal.yaml.part.jinja2, ansible/roles/kraken.fabric/kraken.fabric.flannel/templates/v1.8/rbac-canal-policy.yaml.jinja2, ansible/roles/kraken.fabric/kraken.fabric.weave/templates/v1.6/weave.yaml.part.jinja2, ansible/roles/kraken.fabric/kraken.fabric.weave/templates/v1.7/weave.yaml.part.jinja2, ansible/roles/kraken.fabric/kraken.fabric.weave/templates/v1.8/weave.yaml.part.jinja2, ansible/roles/kraken.nodePool/kraken.nodePool.master/templates/units.kubelet.part.jinja2, ansible/roles/kraken.nodePool/kraken.nodePool.node/templates/units.kubelet.part.jinja2, ansible/roles/kraken.rbac/templates/v1.6/rbac-default-policy.yaml.jinja2, ansible/roles/kraken.rbac/templates/v1.7/rbac-default-policy.yaml.jinja2, ansible/roles/kraken.rbac/templates/v1.8/rbac-default-policy.yaml.jinja2, ansible/roles/kraken.services/defaults/main.yaml, ansible/roles/kraken.services/files/v1.6/helm-rbac-config.yaml, ansible/roles/kraken.services/files/v1.7/helm-rbac-config.yaml, ansible/roles/kraken.services/files/v1.8/helm-rbac-config.yaml, ansible/roles/kraken.services/tasks/run-services.yaml, ansible/roles/kraken.services/templates/v1.6/dns.yaml.jinja2, ansible/roles/kraken.services/templates/v1.6/rbac-dns-policy.yaml.jinja2, ansible/roles/kraken.services/templates/v1.7/dns.yaml.jinja2, ansible/roles/kraken.services/templates/v1.7/rbac-dns-policy.yaml.jinja2, ansible/roles/kraken.services/templates/v1.8/dns.yaml.jinja2, ansible/roles/kraken.services/templates/v1.8/rbac-dns-policy.yaml.jinja2
adds support for kubernetes 1.9 to kraken and sets as default.
fixes #978
=> Kubernetes 1.9

.gitlab-ci.yml
fixes: https://github.com/samsung-cnct/kraken-lib/issues/1040
=> kraken-tools version env variable for gitlab-ci file

ansible/roles/kraken.config/files/config.yaml
patch release updates for calicoCni and calicoNode
part of samsung-cnct/issues#97
=> update calico versions

.gitlab-ci.yml, CONTRIBUTING.md, Documentation/UPGRADING_KUBERNETES.md, ansible/roles/kraken.config/files/config.yaml, build-scripts/conformance-tests, build-scripts/update-generated-config.sh, hack/gen-test-config.sh
adds support for testing non-default versions of k8s in kraken-lib
=> [BAC-105] multiple k8s versions ci test all

.gitlab-ci.yml, build-scripts/docker-update.sh
need to sort out why the command to re-write the dockerfile is failing.
EDIT:  the problem was that the dockerfile re-writing script was attempting to use `/bin/bash` which isn't present in docker image `docker:latest`.  We don't need anything in bash so I switched the shebang to sh.  script works now.
=> [BAC-147] fix kraken-lib release process

ansible/roles/kraken.config/files/config.yaml, ansible/roles/kraken.config/files/gke-config.yaml
this was found experimentally.  full details can be found in listed JIRA issue.
=> Pin coreos version to resolve e2e udp failure
