- ansible/roles/kraken.config/files/config.yaml
the existing defaults don't work with k2cli, let's see if this does (and
whether it breaks the non-k2cli case on jenkins?)
> Drop use of expanduser in default config

- ansible/roles/kraken.provider/kraken.provider.aws/templates/kraken.provider.aws.module.etcd.tf.jinja2
- ansible/roles/kraken.provider/kraken.provider.aws/templates/kraken.provider.aws.module.master.tf.jinja2
- ansible/roles/kraken.ssh/kraken.ssh.aws/tasks/main.yml
master had its name hardcoded to something other then the pool name
etcd nodes are no longer autoscaled
moved the etcd node index to start at one to agree with the ssh
config indexing
This resolves https://github.com/samsung-cnct/k2/issues/67
> allow all nodes to show up in the ssh_config

- ansible/roles/kraken.master/kraken.master.docker/templates/api-server-manifest.yaml.jinja2
for some reason this didn't matter in versions <= 1.4
Tested by hand on a 1.5 hyperkube cluster
> Correcting the SSL directory

- ansible/roles/kraken.config/files/config.yaml
- ansible/roles/kraken.config/tasks/main.yml
- ansible/roles/kraken.config/tasks/set-oidc-info.yaml
- ansible/roles/kraken.master/kraken.master.docker/templates/api-server-manifest.yaml.jinja2
- ansible/roles/kraken.provider/kraken.provider.aws/templates/kraken.provider.aws.module.master.tf.jinja2
- ansible/roles/kraken.services/tasks/generate-oidc-cert.yaml
- ansible/roles/kraken.services/tasks/main.yml
- ansible/roles/kraken.services/templates/service-values.yaml.jinja2
default, it disabled
to use
need to define 
```
kraken_config:
kubeAuth:
oidc:
service_name: dex
```
also dex service
```
-
name: dex
repo: atlas
chart: dex
version: 0.1.0
namespace: kube-system
values:
Dex:
Issuer: https://dex.keyolk.kube.cluster.io:30443
Connector:
Google:
ClientId: ODc2MDc2NjM5NDQ0LW8zdTIzZjY5ZGlsdXMxYTBkNzd0ZHQxb3FzMWZpaDViLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29t
ClientSecret: T0pMc0FLeUpsY2ZjaUtnbkhzaHVwZjQ4
DexApp:
RedirectUri: http://dex.keyolk.kube.cluster.io:30080/callback
```
one of ugly thing that
I didnt found proper way to
get oidc configuration from service values.
like issuer url and redirect url : (
may we can use another oidc provider
so the object 'kubeAuth.oidc' should dynamically get proper value from given service values.
> Support oidc auth using dex.

- Documentation/kraken-configs/deployments/aws.md
- README.md
Add documentation to clarify the expectation that file paths must be
reachable via the mapped volume within the docker container.
Fixes #128
> Add documentation to clarify file paths

- ansible/roles/kraken.node/kraken.node.docker/templates/units.kubelet.part.jinja2
- ansible/roles/kraken.provider/kraken.provider.aws/templates/kraken.provider.aws.module.vpc.tf.jinja2
please see: https://github.com/samsung-cnct/k2/issues/159 for a full
description
tl;dr there's a bug that means we need to set the vpc domain to be
'ec2.internal' and not override the hostname.  its a combo between
the aws provider and some new e2e tests.
> updates to deal with new conformance tests

- ansible/roles/kraken.provider/kraken.provider.aws/tasks/aws-certs-generate.yaml
- ansible/roles/kraken.readiness/tasks/generate-admin-cert.yaml
- ansible/roles/kraken.services/tasks/generate-oidc-cert.yaml
- bin/utils.sh
Move most temporary configuration paths out of `$HOME` or moved files we want to keep to the `--output` path.
Tested by setting `HOME` to a read-only path with no access errors.
Fixes #97
> Prevent k2 from stomping on user files

- ansible/roles/kraken.config/files/config.yaml
> Update default k2 config to use k8s 1.5.2 required by latest helm

- README.md
- ansible/roles/kraken.config/files/config.yaml
- ansible/roles/kraken.fabric/kraken.fabric.flannel/tasks/main.yml
- ansible/roles/kraken.services/tasks/run-services.yaml
- ansible/roles/kraken.ssh/kraken.ssh.aws/tasks/main.yml
- bin/utils.sh
Revert `mkdir -d` substitution for $HOME
Document how to map the needed files instead of $HOME
Add documentation to the README.md for binding just the files we need
for K2 instead of the entire home directory. This prevents the K2
processes from writing potentially overwriting files in the user's home
directory when running as a container.
Fixes #181 and is associated with #97
Similar changes to k2cli should be done, https://github.com/samsung-cnct/k2cli/issues/51
> Don't use temporary directory for $HOME

- ansible/roles/kraken.fabric/kraken.fabric.flannel/defaults/main.yml
- ansible/roles/kraken.fabric/kraken.fabric.flannel/tasks/main.yml
- ansible/roles/kraken.provider/kraken.provider.aws/tasks/aws-action.yaml
- ansible/roles/kraken.readiness/tasks/do-wait.yaml
- ansible/roles/kraken.services/defaults/main.yml
- ansible/roles/kraken.services/tasks/kill-services.yaml
- ansible/roles/kraken.services/tasks/main.yml
- ansible/roles/kraken.services/tasks/run-services.yaml
Rather than using fixed-length pauses, use loops to test if the thing we're pausing for has completed. This allows each of the former pauses to be shorter under many conditions.
Fixes #129
> Use deterministic pauses rather than fixed-length ones.

- ansible/roles/kraken.fabric/kraken.fabric.flannel/tasks/main.yml
On a second "up" run, `Ensure the kube-networking namespace exists`
failed with:
> "Error from server: namespaces \"kube-networking\" already exists", "stdout"
This checks to see if the namespace has already been created and skips
creation if it does.
> Check if the kube-networking namespace exists

- ansible/roles/kraken.provider/kraken.provider.aws/templates/kraken.provider.aws.module.master.tf.jinja2
Since the ELB health checks expire in 200 seconds, often the api server
is not yet listening. Extend the check interval to 45 seconds to allow a
450 second start time.
> Master nodes are taking up to 4.5 minutes to be listening

- ansible/roles/kraken.provider/kraken.provider.aws/templates/kraken.provider.aws.module.master.tf.jinja2
The aws auto scale group can be configured with a health check grace
period. This allows us to have shorter duration health checks to respond
to needs faster, while still giving the instance time to start all its
services.
> Use short health check intervals and a long grace period

- ansible/roles/kraken.provider/kraken.provider.aws/tasks/aws-action.yaml
- ansible/roles/kraken.services/tasks/main.yml
If `up` fails for whatever reason, `down` should still delete the cluster.
> Delete cluster when not fully up

- README.md
- ansible/roles/kraken.provider/kraken.provider.aws/tasks/aws-action.yaml
terraform 0.8.6 seems to be able to remove the dns entries just fine.
Without an upstream issue to track, I think this workaround is no longer
necessary.
> Let terraform remove the dns entries

- ansible/roles/kraken.config/filter_plugins/is_empty.py
- ansible/roles/kraken.config/tasks/main.yaml
This test eliminates long cumbersome definition tests like
```
(kraken_config.providerConfig.type is undefined) or (kraken_config.providerConfig.type is none) or (kraken_config.providerConfig.type|trim == '')
```
with
```
kraken_config.providerConfig.type | is_empty
```
> Add is_empty test

- .pre-commit-config.yaml
- DEVELOPERS.md
Added config file for [pre-commit](http://pre-commit.com/)
Fixes #251 
Requires the installation of [pre-commit](http://pre-commit.com/) on your dev environment to actually do anything.
> Added pre-commit ansible linting

- ansible/roles/kraken.services/tasks/run-services.yaml
Test to ensure kubectl returned 0 before testing its output in case it
failed and did not produce json. This will prevent an early failure in
the until loop if kubectl errored for some reason.
Fixes #252
> Test success before testing json output

- ansible/roles/kraken.fabric/kraken.fabric.flannel/tasks/main.yaml
I mistakenly thought that a retries clause without an until would retry
until the command succeeded. The ansible documentation is insufficient
on this point.
> Add an "until" to test the retry against

- ansible/roles/kraken.provider/kraken.provider.aws/templates/kraken.provider.aws.tf.jinja2
100 retries with an exponential backoff leads to wait times between
attemps in the millenia. Reduce to 8 which is only in the realm of
minutes.
> Reduce terraform retries

- hack/dockerdev
This script can be used to stand up a k2 container for development
This maps any files or directories specified in your config.yaml file
into the docker container (just like k2cli does) and maps your development
tree over the contents of the quay container.
> Add bash script to ease docker configuration for hacking k2

- bin/utils.sh
- down.sh
- up.sh
- update.sh
via a -v, let me know what you think and we can address it in a different manner if you wish.
example:
```
./up.sh -o ~/.kraken/ -c ~/.kraken/ae-cynosure_config.yaml -t 'ssh' -v '-vvv'
```
> I submit for your approval setting verbosity for ansible 

- ansible/roles/kraken.config/tasks/main.yaml
> Ensure each nodePool corresponds to exactly one of the node roles

- ansible/roles/kraken.config/files/config.yaml
one. In a future with federated clusters, this value will not
be the same for all clusters.
> Make readiness a cluster level property instead of a top level

- ansible/roles/kraken.config/tasks/main.yaml
from issue #271 
Will have to update for gke k8s minor version fact as well. Unclear if this should wait until k2recon merges back with master, or just pull it from a file and make changes right now. @coffeepac ?
> uses kubeConfig from new config file for k8s minor version fact in aws

- ansible/roles/kraken.master/kraken.master.docker/templates/units.kubelet.part.jinja2
- ansible/roles/kraken.node/kraken.node.docker/templates/units.kubelet.part.jinja2
`--config` has been deprecated since kube 1.4.   replace with `--pod-manifest-path`
https://github.com/samsung-cnct/k2/issues/341
> K2-341 fix deprecated argument

- ansible/roles/kraken.services/tasks/kill-services.yaml
reversed order of `when` clause to short-circuit on `kraken_action == down `
> changed order of conditional on clean up services

- ansible/roles/kraken.config/tasks/main.yaml
- ansible/roles/kraken.config/tasks/setup.yaml
For AWS this will gather all kubernetes minor versions from all clusters specified in the config file and assign them to a top-level key called kubernetes_minor_version.
You can now look up each cluster's minor version by cluster name as follows:
kubernetes_minor_versions.<clusterName> and it should tell you the minor version.
This partially fulfills #345.
As per #337 the GKE work is still left to do.
> Kubernetes minor versions fact

- ansible/roles/kraken.fabric/kraken.fabric.flannel/tasks/deploy-canal.yaml
- ansible/roles/kraken.readiness/tasks/bootstrap-default-rbac-policy.yaml
- ansible/roles/kraken.readiness/tasks/do-wait.yaml
- ansible/roles/kraken.readiness/tasks/generate-admin-kubeconfig.yaml
- ansible/roles/kraken.services/tasks/kill-services.yaml
- ansible/roles/kraken.services/tasks/run-services.yaml
This sets a kubectl fact in kraken.services/tasks/kill-services and kraken.services/tasks/run-services so that each cluster will use the appropriate version of kubectl.
> Kubectl for all versions and all clusters

- hack/dockerdev
This adds a `-r` argument to specify the root config directory.  
If it is not specified, then $HOME will be used.
> Add ability to use non-HOME as base directory

- ansible/roles/kraken.config/files/config.yaml
- ansible/roles/kraken.config/files/gke-config.yaml
the inclusion by default of the central-logging repo means that several specs needed to get updated. We needed more clusterNodes slightly different instance types to handle logging
> update defaults for central-logging

- ansible/roles/kraken.config/tasks/main.yaml
quick check that will fail on cluster up if user tries to stand up more than one cluster.
> check for number of clusters

- build-scripts/update-generated-config.sh
GKE only accepts lower case letters in the cluster names.  AWS is fine either way so we're going to constrain to GKE levels.
> all letters need be lowercase because of GKE

- Jenkinsfile
- ansible/roles/kraken.config/files/gke-config.yaml
- build-scripts/conformance-tests.sh
- build-scripts/e2etester-docker/Makefile
the 'tee' portion in a command (and subsequent workarounds) were causing all runs to fail.  I believe the PIPESTATUS workaround is not available in the sh shell.  we no longer need to save off the build-log output file.
removal of this guff has produced at least one e2e successful run.  This PR should not be merged until the new jenkins job passes.
> allow e2e tests to succeed

- README.md
Replaced YOURCLUSTER, foo, and <your_config> in example command lines with ${CLUSTER}.
Left YOURCLUSTER for examples inside the config file.
Updated helm output and usage, especially for search and install of kubernetes-dashboard.
Added instructions to bring the cluster up prior to the examples for accessing the cluster.
> Update README.md, mostly to use ${CLUSTER}.

- ansible/roles/kraken.cluster_common/templates/help.txt.jinja2
for terminal commands with k2, I need to edit this command and replace `root` with `$HOME`, which was difficult when the command was three lines long. I also removed an extra `helm` hiding in there
> removed redundant helm and made into one-liner for ease of cut and paste

- ansible/roles/kraken.cluster_common/tasks/main.yaml
Was previously causing this error:
```TASK [roles/kraken.cluster_common : Generate shell command help text] **********
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to find 'templates/help.txt.jinja2' in expected paths."}
```
> fixed pathing of template in kraken.cluster_common

- ansible/roles/kraken.fabric/kraken.fabric.flannel/tasks/main.yaml
- ansible/roles/kraken.provider/kraken.provider.aws/tasks/main.yaml
- ansible/roles/kraken.provider/kraken.provider.gke/tasks/create-cluster.yaml
- ansible/roles/kraken.provider/kraken.provider.gke/tasks/main.yaml
- ansible/roles/kraken.ssh/kraken.ssh.selector/tasks/main.yaml
k2/ansible/roles/kraken.fabric/kraken.fabric.flannel/tasks/main.yaml
```
- name: Wait for api server
wait_for:
host: "{{ item | regex_replace('https://','') }}"
port: 443
timeout: 600
with_items: "{{ api_servers }}"
vars:
kubefn: "{{ config_base | expanduser }}/{{ cluster.name }}/admin.kubeconfig"
kubeconfig: "{{ kubefn | is_file | ternary( kubefn, '/dev/null' ) }}"
api_servers: "{{ lookup('file', kubeconfig) | from_yaml | json_query('clusters[*].cluster.server') }}"
when: not ( dryrun | bool )
```
error log
```
fatal: [localhost]: FAILED! => {"failed": true, "msg": "{{ lookup('file', kubeconfig) | from_yaml | json_query('clusters[*].cluster.server') }}: An unhandled exception occurred while running the lookup plugin 'file'. Error was a <class 'ansible.errors.AnsibleError'>, original …
```
> Dryrun tags bug fixing

- Jenkinsfile
- ansible/roles/kraken.config/files/config.yaml
- ansible/roles/kraken.config/files/gke-config.yaml
this makes 1.6.4 the default version of kubernetes.  Temporarily we are removing the central logging chart because we have not yet written the rbac specs for fluentd. This will be covered in the 0.3 milestone, and then it can be added back in.
> made 1.6.4 default

- ansible/roles/kraken.fabric/kraken.fabric.flannel/templates/namespace.yaml.part.jinja2
- ansible/roles/kraken.fabric/kraken.fabric.weave/templates/namespace.yaml.part.jinja2
as noted in #542 these two files have 'piVersion' fields instead of 'apiVersion' fields.
> correct the yaml file

- ansible/roles/kraken.config/tasks/main.yaml
- ansible/roles/kraken.rbac/tasks/build-access.yaml
- ansible/roles/kraken.readiness/tasks/do-wait.yaml
Example of warnings we dont want to keep seeing:
TASK [kraken.config : Do not allow multiple clusters in config] ***************************************************************************
[WARNING]: when statements should not include jinja2 templating delimiters such as {{ }} or {% %}. Found: {{ kraken_config.clusters |
length | int > 1 }}
TASK [roles/kraken.rbac : Wait for api server response before continuing] *****************************************************************
[WARNING]: when statements should not include jinja2 templating delimiters such as {{ }} or {% %}. Found: {{
rbac_get_nodes_result.stdout_lines | length }} >= 1 | int
TASK [roles/kraken.readiness : Get all nodes] ********************************************************************************************* …
> doing my part to remove the jinja2 templating warning.

- .gitignore
- ansible/roles/kraken.config/files/config.yaml
- ansible/roles/kraken.config/files/gke-config.yaml
- ansible/roles/kraken.fabric/kraken.fabric.weave/templates/v1.6/weave.yaml.part.jinja2
- ansible/roles/kraken.fabric/kraken.fabric.weave/templates/weave.yaml.part.jinja2
- schemas/config/v1/weaveFabricNetwork.json
- schemas/config/v1/weaveFabricOptions.json
Default version of weave-net seems to have an issue of resolving dns names within pods. Issue seems to be fixed on version 1.9.8, bumping defaults to that version.
> Bumping default version of weave-net to latest: 1.9.8. 

- ansible/update.yaml
- update.sh
Update action does not need tags for now, so references to them were removed. 
This is part of [K2cli issue](https://github.com/samsung-cnct/k2cli/issues/70).
> deleted tags from update actions

- Documentation/kraken-configs/provider/aws.md
- ansible/roles/kraken.provider/kraken.provider.aws/tasks/aws-template.yaml
- ansible/roles/kraken.provider/kraken.provider.aws/templates/kraken.provider.aws.module.route53.tf.jinja2
- ansible/roles/kraken.provider/kraken.provider.aws/templates/kraken.provider.aws.module.vpc.tf.jinja2
- ansible/roles/kraken.provider/kraken.provider.aws/templates/kraken.provider.aws.tf.jinja2
- schemas/config/v1/awsProviderConfig.json
- schemas/config/v1/awsVpcConfig.json
to use a pre-existing VPC a user will need to specify the vpc id,
a route table in that vpc and the id of the default security
group of the vpc.  the user should also be certain they have set
up all of the network CIDRs correctly as K2 will not help with
that.
this closes #124
> allow a user to specify a pre-existing VPC for aws clusters

- ansible/roles/kraken.provider/kraken.provider.aws/templates/kraken.provider.aws.module.subnet.tf.jinja2
- ansible/roles/kraken.provider/kraken.provider.aws/templates/kraken.provider.aws.module.vpc.tf.jinja2
- schemas/config/v1/awsPreexistingSubnetConfig.json
- schemas/config/v1/awsProviderConfig.json
- schemas/config/v1/awsVpcConfig.json
force user to supply subnet when BYOing a VPC.  
set other subnet option to be optional (don't need both)
set route_table_id as optional and set description to be DEPRECATED.
this closes #583
> make subnet part of pre-existing VPC config

- hack/dockerdev
Just some simple command line option parsing changes to support long options and add some help text.
Also a minor change to allow a manually configured MAPPINGS environment variable to be used to manually add additional `-v source:dest` docker switches.
> Enhance command line processing

- down.sh
- lib/common.sh
- up.sh
- update.sh
Added graceful error handling for cases where someone does not have k2-crash-app installed or log file is not in expected location 
Created 3 functions to deal with up/down/update separately, since each one calls different functions depending on success or failure - at this point I think it would be less confusing and less code to just put the k2-crash-app trigger inline in the up.sh/down.sh/update.sh, like I originally had it, but let me know what you think.
> Error handling, separate functions for up/down/update

- ansible/roles/kraken.config/files/gke-config.yaml
part of weekly review, this will knock the CI runs back to 4 minutes instead of 45 for the GKE path.
> use GKE default of 1.6.4

- computed_kubectl.sh
- max_k8s_version.sh
$0 will contain the entire path being called which can inject
additional path segments into the file name.  this causes
problems.
the desire was to have the base name that mktemp creates be the
script name so its hardcoded now
> do not use $0 for call to mktemp

- ansible/roles/kraken.config/files/gke-config.yaml
the aws default uses $HOME and using `~` causes problems in k2cli
> don't use tilde, use $HOME

- Documentation/kraken-configs/helmconfigs.md
- README.md
- ansible/roles/kraken.config/files/config.yaml
- ansible/roles/kraken.provider/kraken.provider.gke/README.md
- ansible/roles/kraken.services/tasks/run-services.yaml
- schemas/config/v1/helmChart.json
Add support for the helm (app registry plugin)[https://github.com/app-registry/appr-helm-plugin] to allow version pinned charts to be used in k2 configs.
Depends on https://github.com/samsung-cnct/k2-tools/pull/84
> Add helm app registry support

- ansible/roles/kraken.fabric/kraken.fabric.flannel/templates/v1.6/canal.yaml.part.jinja2
- ansible/roles/kraken.fabric/kraken.fabric.weave/templates/v1.6/weave.yaml.part.jinja2
- ansible/roles/kraken.nodePool/kraken.nodePool.master/templates/v1.6/api-server-manifest.yaml.jinja2
- ansible/roles/kraken.nodePool/kraken.nodePool.master/templates/v1.6/controller-manager-manifest.yaml.jinja2
- ansible/roles/kraken.nodePool/kraken.nodePool.master/templates/v1.6/kube-proxy-manifest.yaml.jinja2
- ansible/roles/kraken.nodePool/kraken.nodePool.master/templates/v1.6/units.kubelet.part.jinja2
removes the register-unschedulable for masters.  now static pods are aligned with master nodes because of taints and tolerations
> taints and tolerations added for master nodepool

- ansible/roles/kraken.config/tasks/set-oidc-info.yaml
The dex chart has changed `Dex` to `dex` to match that standards produced upstream. Change this to match.
> Changed the case to match upstream standards

- Jenkinsfile
The groovy regex tester, `==~` was failing to find the matching text in
every possible test I could throw at it. Instead, use the string method,
`contains` to ensure the git org string exists in the scm uri.
> avoid groovy regex tester fail

- ansible/roles/kraken.config/files/config.yaml
- ansible/roles/kraken.provider/kraken.provider.aws/templates/kraken.provider.aws.module.master.tf.jinja2
- ansible/roles/kraken.provider/kraken.provider.aws/templates/kraken.provider.aws.tf.jinja2
- schemas/config/v1/apiServerConfig.json
- schemas/config/v1/awsLoadBalancerConfig.json
resolves: https://github.com/samsung-cnct/k2/issues/658
- Consistent spacing for the generated config file
- Code to allow subnets for load balancers, (search by name go get ids)
- Removed extraneous loadbalancer config.
> allow aws loadbalancers the option to select subnets.

- ansible/roles/kraken.provider/kraken.provider.aws/tasks/wait-for-etcd.yaml
- Added a check to run task: `Wait for etcd cluster to form` only when public ips are available.
should resolve: https://github.com/samsung-cnct/k2/issues/671
> k2 expecting to get cluster health from a private topology via ssh

- ansible/roles/kraken.services/tasks/kill-services.yaml
it is probably/guarnateed that there will be ELBs in the VPC that
do not belong to kubernetes.
This doesn't resolve the underlying issue that the ansible module
can easily overwhelm the API threshold but it does unblock people
who certainly don't want to block on this.
long term fix:  #676 
fixes: #635 
fixes: #644
> if in a BYO vpc scenario, do not block for all ELBs

- ansible/roles/kraken.nodePool/kraken.nodePool.etcd/templates/etcd.units.etcd.part.jinja2
Etcd node discovery via DNS SRV requires that the `--name` parameter had a unique value for each node.
Currently all etcd nodes have the name `etcdetcd` and all events nodes have the name `etcdetcdevents`.
This can result in discovery incorrectly thinking all nodes are discovered, when they are not.  
Exact results of this bug are unclear, however clusters may have been evaluated as "up" prematurely.
> Etcd Node Name Should be Unique for Discovery

- .gitignore
- Documentation/README.md
- ansible/roles/kraken.cluster_common/templates/v1.5/help.txt.jinja2
- ansible/roles/kraken.config/tasks/check-update.yaml
- ansible/roles/kraken.config/tasks/cluster_loop.yaml
- ansible/roles/kraken.config/tasks/helm-versioning.yaml
- ansible/roles/kraken.config/tasks/helm.yaml
- ansible/roles/kraken.config/tasks/kubectl.yaml
- ansible/roles/kraken.config/tasks/main.yaml
- ansible/roles/kraken.config/tasks/setup.yaml
- ansible/roles/kraken.services/tasks/aws_config.yaml
- ansible/roles/kraken.services/tasks/generate-oidc-cert.yaml
- ansible/roles/kraken.services/tasks/kill-services.yaml
- ansible/roles/kraken.services/tasks/main.yaml
- ansible/roles/kraken.services/tasks/run-services.yaml
This moves duplicated code which uses the found versions to choose which `helm` and `kubectl` executable path to use to configure so it need only be run once.
* Fixes DRY issues
* Fixes linting errors
* Allows for frigid temperatures in the underworld
* Modified `while` `and`s to be lists for readability
> Move helm and kubernetes command configuration to config

- ansible/roles/kraken.services/tasks/main.yaml
- ansible/roles/kraken.services/tasks/manage-services.yaml
Make helm upgrade rather than delete and install.
* Only run kill-services on `down`
* Add `manage-services` to be run on `update` instead
* Upgrade tiller as needed to match helm version
Fixes #453
> upgrade services on k2 update

- ansible/roles/kraken.config/tasks/helm.yaml
- schemas/config/v1/cluster.json
Added a fact in helm.yaml to convert dashes to underscores in cluster name to use in helm_override.
Updated schema to disallow underscores in cluster name.
Fixes https://github.com/samsung-cnct/k2/issues/513
> Convert dashes to underscores in cluster name

- ansible/roles/kraken.rbac/defaults/main.yaml
- ansible/roles/kraken.rbac/tasks/bootstrap-default-rbac-policy.yaml
- ansible/roles/kraken.rbac/tasks/build-access.yaml
Add retries to the initial rbac deployment to ensure success.
This is attempting to work around the very inconsistent "file missing" error that has cropped up in 1.7.1.
Reference: #703 
Also, move "magic numbers" into defaults while we're editing this code.
> Add a couple retries on default rbac deploy

- hack/parallel-conformance.sh
the current args are NOT turning off the color control chars in the e2e logs (though they should).
> try to remove color

- ansible/roles/kraken.assembler/tasks/nodes.yaml
Appending files does so in a random order. This causes a change to the
cloud-config which will cause all the ASG to get recreated. This is
undesired behavior so avoid changing cloud-config.
> Don't recreate cloud-config if it exists

- ansible/roles/kraken.config/tasks/check-update.yaml
This fixes a missing plural in nodepool update error messages. 
@venezia does this help a bit?
> fixed confusing typo in command line prompt

- CODEOWNERS
three people are in the team right now, I want to see how review requests get allocated.  we can change the team membership if we like how this functions.
> Use a public team for default reviews

- ansible/roles/kraken.provider/kraken.provider.aws/templates/kraken.provider.aws.module.cluster_secgroup.tf.jinja2
- ansible/roles/kraken.provider/kraken.provider.aws/templates/kraken.provider.aws.module.vpc.tf.jinja2
- ansible/roles/kraken.provider/kraken.provider.aws/templates/v1.5/kraken.provider.aws.module.cluster_secgroup.tf.jinja2
- ansible/roles/kraken.provider/kraken.provider.aws/templates/v1.5/kraken.provider.aws.module.vpc.tf.jinja2
- schemas/config/v1/awsProviderConfig.json
kraken creates the vpc route table and the vpc security group , however
kubernetes will make modifications to both assets as the cluster runs.
we should not let kraken modify either of these resources going forward.
there is no way to specify custom routes in the config file so we are fine there
we need to modify the documentation on the security group to specify that
the ingress and egress rules for the security will only be applied at cluster
creation.
Fixes: #817
> prevent kraken from removing some kubernetes created resources

- ansible/roles/kraken.readiness/tasks/do-wait.yaml
kubectl for version 1.6.4 does not understand the flag --schema-cache-dir, removing to continue support of 1.6
> [role/kraken.readiness/tasks/do-wait] removed --schema-cache-dir

- ansible/roles/kraken.post/tasks/main.yaml
- ansible/update.yaml
we have been running all roles weather needed or not on update to
ensure we don't miss anything.  since the update process was added
we have cleaned up the interfaces between roles significantly and
can now split out exactly which roles are necessary for making
changes to a running kraken-managed kubernetes cluster
> trim down roles being run for update

- ansible/roles/kraken.config/files/gke-config.yaml
changed this week, CI runs are taking 45 minutes again.
> update default gke version to 1.7.5

- bin/computed_kubectl.sh
- bin/max_k8s_version.sh
changed output of computed_kubectl to suppress ansible output, optionally allows you to turn it on via verbosity flag.
> [Feature Request] kraken kubectl suppress ansible output by default.

- ansible/roles/kraken.cluster_common/templates/locksmith.part.jinja2
Alter the template to produce valid yaml for the group key, and to use
the nodePool name if a locksmith group is not defined instead of
the string, "item.name".
Fixes #841
> Produce valid yaml for the group key

- ansible/roles/kraken.provider/kraken.provider.gke/tasks/main.yaml
ansible's boolean evaluation is 'short circuit-able' so we can test
for the parent object being defined and parsing will stop before
checking for the child.  this will prevent error messages that get
ignored and make the system slightly safer
> remove the 'ignore errors' for running the taints task in gke

- ansible/update.yaml
we should be waiting for any new nodepools to be created before we
generate the ssh config file
> add a readiness wait back to update.yaml

- ansible/roles/kraken.services/tasks/kill-services.yaml
- ansible/roles/kraken.services/tasks/manage-services.yaml
- ansible/roles/kraken.services/tasks/run-services.yaml
this change allows the app registry plugin to execute the epxected
version of helm when it runs.  the app registry plugin is called
from helm via `helm appr` and it will make a call back to helm via
a shell invocation `helm`.  This means app registry will execute
whichever helm it finds in the system path.  We don't want this.
we now put the path for the calling helm at the front of the system
path so it gets called by the app registry plugin
> helm appr pathing sorted

- ansible/roles/kraken.nodePool/kraken.nodePool.master/templates/api-server-manifest.yaml.jinja2
- ansible/roles/kraken.nodePool/kraken.nodePool.master/templates/v1.5/api-server-manifest.yaml.jinja2
- ansible/roles/kraken.nodePool/kraken.nodePool.master/templates/v1.6/api-server-manifest.yaml.jinja2
- ansible/roles/kraken.nodePool/kraken.nodePool.master/templates/v1.7/api-server-manifest.yaml.jinja2
this is necessary in kubernetes versions >= 1.8 to enable cronjobs, which will be needed for curator (for logging) to wipe out old logs and keep out ES pods up and running. 
Note*    CronJob resource in batch/v2alpha1 API group has been deprecated starting from cluster version 1.8. We will need to switch to using batch/v1beta1, instead, which will be enabled by default in the API server.
> add batch/v2alpha1 for cronjobs

- CONTRIBUTING.md
first crack at creating an issue labeling guide/explanation.
> add an 'issue labeling' section to contributing

- ansible/roles/kraken.config/files/config.yaml
on etcd nodes, docker is not used.  This removes a 100GB EBS volume that serves only to increase someone's aws bill.
Would like it if kraken could support `io1` disk type (needs additional option for iops setting)
> Adjusting config.yaml to remove unnecessary mount

- ansible/roles/kraken.cluster_common/tasks/certificate_authority.yaml
The CA is not dereferenced for role inclusion so this logic should
reside in drunkensmee.
> Remove logic applied to the CA

- schemas/config/v1/cluster.json
Change max length for cluster names to 21. AWS ELB name max length is 32 and we append `-master-elb` which add 11 chars. 
Fixes: https://github.com/samsung-cnct/kraken-lib/issues/883
> Changed max len of cluster name to not hit max len for AWS ELB name 

- ansible/roles/kraken.config/defaults/main.yaml
- ansible/roles/kraken.nodePool/kraken.nodePool.etcd/templates/etcd.units.kraken-etcd-ssl.part.jinja2
- ansible/roles/kraken.nodePool/kraken.nodePool.etcd/templates/v1.5/etcd.units.kraken-etcd-ssl.part.jinja2
- ansible/roles/kraken.nodePool/kraken.nodePool.master/tasks/each-cluster-nodepool.yaml
- ansible/roles/kraken.nodePool/kraken.nodePool.master/templates/proxy-kubeconfig.jinja2
- ansible/roles/kraken.nodePool/kraken.nodePool.master/templates/units.kraken-apiserver-ssl.part.jinja2
- ansible/roles/kraken.nodePool/kraken.nodePool.master/templates/v1.5/units.kraken-apiserver-ssl.part.jinja2
- ansible/roles/kraken.nodePool/kraken.nodePool.node/tasks/each-cluster-nodepool.yaml
- ansible/roles/kraken.nodePool/kraken.nodePool.node/templates/kube-proxy-manifest.yaml.jinja2
- ansible/roles/kraken.nodePool/kraken.nodePool.node/templates/proxy-kubeconfig.jinja2
- ansible/roles/kraken.nodePool/kraken.nodePool.node/templates/units.kraken-worker-ssl.part.jinja2
- ansible/roles/kraken.nodePool/kraken.nodePool.node/templates/v1.5/units.kraken-worker-ssl.part.jinja2
kubelet and kube-proxy were sharing the same kubeconfig. Using the
correct username (CN) and group (O) in the node cert breaks kube-proxy.
This creates a cert specifically for kube-proxy.
This PR requires changes in drunkensmee (The referenced container tag is
the github commit sha).
> Use cert specifically for kube-proxy

- hack/parallel-conformance.sh
arguments requiring two dashs.
> Change arguments to hack/e2e.go to account for single letter

- ansible/library/compatibility.py
- ansible/roles/kraken.config/tasks/validate-config.yaml
version other than v2.6.1 (fixes #901).
> Do not allow k8s 1.7 clusters to use any other calicoNode container

- ansible/library/compatibility.py
was missing a level on the mapping to return the default fabric in
the case of using a 1.7 default version of kubernetes
> correct depth for returning fabric

- ansible/roles/kraken.services/files/helm-rbac-config.yaml
- ansible/roles/kraken.services/files/kraken-namespace.yaml
- ansible/roles/kraken.services/tasks/run-services.yaml
this will install till into a `--tiller-namespace` of `kraken`. Currently it is setup to run tiller as a cluster-admin, giving it permission over all namespaces.  We can change this if folks want, to instead give it access only over `kraken`, `kube-networking`, `kube-system`, and any other namespaces listed in `helmConfigs`.  We could also open another ticket if we think this is good enough for now. 
I would love feedback on if anyone thinks it is necessary to change the info at cluster creation given to a user who runs `dockerdev`, seeing as right now the old: `to use helm`... isn't going to give them access to the releases.  They would need to be instructed to add `--tiler-namespace kraken` to their helm command.
> Tiller namespace

- ansible/up.yaml
`services_only` was removed: https://github.com/samsung-cnct/kraken-lib/pull/488
I hit a dev edge case where I really needed `services_only`. Adding it back in. 
It's also still in the documentation.
> Added back 'services_only' tag

- ansible/roles/kraken.config/files/gke-config.yaml
> Update default k8s version for GKE to 1.7.8 to avoid auto-upgrade

- Documentation/security/README.md
- Documentation/security/example/config.yaml
- ansible/roles/kraken.config/files/config-private-topology.yaml
- ansible/roles/kraken.config/files/config.yaml
- ansible/roles/kraken.config/files/gke-config.yaml
- docs/index.html
- schemas/config/v1/kubeAuthAuthzEntry.json
I removed the 1.5 super_user property from rbacKubeAuth authz in our config (since we now support minor releases 1.6.x, 1.7.x, and 1.8.x).  Now authz only has an empty rbac property.  This is used in many places to test if RBAC is defined.  I am leaving this in so that RBAC could be turned off, or so we could add additional future properties to RBAC.
> Removed 1.5 super_user references

- ansible/roles/kraken.provider/kraken.provider.aws/tasks/main.yaml
- ansible/roles/kraken.provider/kraken.provider.aws/tasks/wait-for-etcd.yaml
- ansible/roles/kraken.provider/kraken.provider.aws/tasks/wait-for-one-etcd.yaml
etcd instances running on the same node will all be checked.
Fixes #702.
> Fix etcd health check so that all results are reported and multiple

- ansible/roles/kraken.nodePool/kraken.nodePool.master/templates/api-server-manifest.yaml.jinja2
- ansible/roles/kraken.nodePool/kraken.nodePool.master/templates/v1.6/api-server-manifest.yaml.jinja2
- schemas/config/v1/apiServerConfig.json
- schemas/config/v1/apiServerFlags.json
Allows for them  to be changed them with our own, for example:
```
apiServerConfigs:
- &defaultApiServer
name: defaultApiServer
kind: apiServer
loadBalancer: cloud
state:
etcd: *defaultEtcd
events:
etcd: *defaultEtcdEvents
flags:
admissionControl: "NamespaceLifecycle,LimitRanger,ServiceAccount,NodeRestriction,PersistentVolumeLabel,DefaultStorageClass,ResourceQuota,DefaultTolerationSeconds,Initializers"
runtimeConfig: "batch/v2alpha1=true,admissionregistration.k8s.io/v1alpha1=true"
```
allows us to now run istio with automatic injection. A configmap may be required in future work.
> admission control and runtime config flags now exposed

- Documentation/tags/README.md
- ansible/roles/kraken.access/tasks/main.yaml
- ansible/roles/kraken.access/tasks/setup-certs.yaml
- ansible/up.yaml
- lib/common.sh
- lib/kraken_arguments.sh
the post_provider ansible tag runs all roles necessary to complete
the configuration of a cluster after it has been provisioned using
cloud-config files generated by kraken.  this is useful when
manually creating the nodes in a new cloud provider and using
kraken for everything else.
this is part of #939
> changes to add a post_provider ansible tag

- README.md
...because k2-charts is no longer maintained.
I currently just included the charts we have recently updated to reflect our "application deployment" best practices.
If you feel other charts from k2-charts or elsewhere are stable enough to officially recommend to users, let me know. 
Fixes: https://github.com/samsung-cnct/kraken-lib/issues/954
> Updated documentation to not reference k2-charts

- Jenkinsfile
- ansible/roles/kraken.config/files/gke-config.yaml
- ansible/roles/kraken.provider/kraken.provider.gke/tasks/create-cluster.yaml
- ansible/roles/kraken.services/tasks/run-services.yaml
Fixes: https://github.com/samsung-cnct/kraken-lib/issues/150
Related to: https://github.com/samsung-cnct/kraken-lib/pull/948
Enables cluster-autoscaling in GKE clusters.
NOTES: 
- There is not a Helm chart for GKE cluster auto-scaling. 
- The `--quiet` flag is in a unconventional location, but it does not work listed after the command on a new line.
> default cluster auto-scaling enabled for GKE clusters

- ansible/roles/kraken.access/defaults/main.yaml
kraken calls the playbook directly so it skips the defaulting that
happens in the shell scripts
> add a default for kubernetes_endpoint in the playbook

- ansible/roles/kraken.config/files/config.yaml
- ansible/roles/kraken.config/files/gke-config.yaml
Did a quick cluster up and get pods for both aws and gke.  Will let CI do the rest
> Updated versions for weave, flannel, and calico

- ansible/roles/kraken.config/files/config.yaml
allows us to deploy logging by default while still testing two
nodepools composed of two different instance types.
> Use m4.large for clusterNodes and c4.large for specialNodes. This

- Documentation/tags/README.md
- ansible/up.yaml
adds a new tag to kraken-lib 'pre_provider' that runs all roles before the provider selector.  This is useful for creating the cloud-config artifacts and stopping.  possibly only useful as a development tool.
> Pre provider

- ansible/roles/kraken.provider/kraken.provider.gke/tasks/create-cluster.yaml
Fail earlier if gke cluster fails to deploy (fixes https://github.com/samsung-cnct/kraken-lib/issues/548)
> Fail earlier if gke cluster fails to deploy

- README.md
We're mentioned as certified here: https://www.cncf.io/announcement/2017/11/13/cloud-native-computing-foundation-launches-certified-kubernetes-program-32-conformant-distributions-platforms/
Add the badges we have earned, and link to the instructions people can use to reproduce the conformance results on their own with kraken
ref: samsung-cnct/kraken#223
> Add certified kubernetes badges

- schemas/config/v1/nodePool.json
Tainting nodepools was added in #758 but the schema does not reflect
that. This corrects that deficiency.
> Allow taints per nodepool

- schemas/config/v1/nodePool.json
Reverts samsung-cnct/kraken-lib#1026
I missed that taints are actually supposed to be under schedulingConfig
> Revert "Allow taints per nodepool"

- hack/kraken-teardown-aws.sh
- hack/kraken-teardown-gke.sh
- hack/kraken-teardown.sh
This is a first stab at the API logic for tearing down clusters that CI leaves (at least) partially deployed after a test failure, currently, and provides for a few other related use-cases.
This first draft _DOES NOT_ actually remove anything, it simply queries the API and prints the proposed `aws` and `gcloud` commands, for review. I'll comment here shortly with example output.
Please raise any concerns here in the PR. 
**Update**: the behavior of `echo`ing the proposed `DELETE` operations is now documented, with the intent of being executed separately; done simply with `| bash` for CI purposes.
> Remove clusters by API query in AWS & GCP

- .gitlab-ci.yml
currently we only save the state from 'up' commands when the command succeeds.  however, if the etcd cluster fails to form, the cluster up fails.  
we still need the artifact here so that the down command will work.
> always save artifacts from 'cluster up'

- bin/max_k8s_version.sh
At some point during the CLI arg refactoring, someone removed a
trailing space that this script was reyling to function.  I have
added it here as a leading space so that I don't have to test
anything else
currently, this means that `kraken tool` doesn't work
> add a space to the CLI args to make them work again

- .gitlab-ci.yml
- build-scripts/benchmark-conf/1.6/master.yaml
- build-scripts/benchmark-conf/1.6/node.yaml
- build-scripts/benchmark-conf/1.7/master.yaml
- build-scripts/benchmark-conf/1.7/node.yaml
- build-scripts/benchmark-conf/1.8/master.yaml
- build-scripts/benchmark-conf/1.8/node.yaml
- build-scripts/benchmark-conf/1.9/master.yaml
- build-scripts/benchmark-conf/1.9/node.yaml
- build-scripts/benchmark-conf/config.yaml
- build-scripts/benchmark-tests
- hack/benchmark-test.sh
**What this PR does / why we need it**: This PR adds a CI job that runs the [kube-bench][2] tool on a Kraken cluster. The kube-bench tool is an implementation of the [CIS Benchmark for Kubernetes][1]. This will allow us to establish a baseline metric in regards to the security posture of a Kraken provisioned cluster.
**Which issue this PR fixes**: fixes #660 ([BAC-102][102])
**How to Verify**
- This PR should invoke the new `test-security:benchmark` (and `benchmark-minus-one` and `benchmark-minus-two`) in the gitlab pipeline. On success of this job the test result artifacts should be associated with the gitlab job. You should be able to verify these files manually.
- Additionally this can be invoked locally with the following command:
```
docker run \
-v ~/.ssh:/root/.ssh \
-v …
```
> [BAC-102] Add kube bench tests to CI (#660)

- ansible/roles/kraken.nodePool/kraken.nodePool.master/templates/units.kubelet.part.jinja2
- ansible/roles/kraken.nodePool/kraken.nodePool.master/templates/v1.6/units.kubelet.part.jinja2
- ansible/roles/kraken.nodePool/kraken.nodePool.master/templates/v1.7/units.kubelet.part.jinja2
the kubelet is responsible for making symlinks from where docker stores
log files (/var/lib/docker/) to where kubernetes says the log file
will be available (/var/lib/pods or /var/lib/containers).  to let
kubelet make these changes on the host, we need to mount the hosts
/var/log or we're just farting around in the kubelet's running
imagefs
> add system log mount to master kubelets
